CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    segment VARCHAR(15) NULL,
    join_date TIMESTAMPTZ NULL DEFAULT NOW(),
    utm_mark VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS farma_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    join_date TIMESTAMPTZ NULL DEFAULT NOW(),
    utm_mark VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id),
    event_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_events_user_id_timestamp
    ON events (user_id, timestamp);

CREATE INDEX IF NOT EXISTS ix_events_user_id
    ON events (user_id);

CREATE INDEX IF NOT EXISTS ix_events_event_name
    ON events (event_name);

CREATE INDEX IF NOT EXISTS ix_events_timestamp
    ON events (timestamp);

CREATE TABLE IF NOT EXISTS farma_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES farma_users (id),
    event_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NULL DEFAULT NOW()
);
