CREATE TABLE IF NOT EXISTS tracked_sheets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service VARCHAR(5) NOT NULL CHECK (service IN ('rpp', 'farma')),
    spreadsheet_id VARCHAR(255) NOT NULL,
    spreadsheet_url TEXT NOT NULL,
    sheet_name VARCHAR(255) NOT NULL,
    sheet_gid BIGINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    poll_interval_seconds INTEGER NOT NULL DEFAULT 600,
    last_seen_row_num INTEGER NULL,
    last_seen_source_fingerprint VARCHAR(128) NULL,
    last_sync_started_at TIMESTAMPTZ NULL,
    last_sync_finished_at TIMESTAMPTZ NULL,
    last_sync_status VARCHAR(7) NULL CHECK (last_sync_status IN ('running', 'ok', 'error')),
    last_sync_error TEXT NULL,
    last_sync_rows_read INTEGER NULL,
    last_sync_rows_inserted INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tracked_sheets_spreadsheet_id_sheet_name
        UNIQUE (spreadsheet_id, sheet_name)
);

CREATE INDEX IF NOT EXISTS ix_tracked_sheets_service_is_active
    ON tracked_sheets (service, is_active);

CREATE TABLE IF NOT EXISTS payment_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service VARCHAR(5) NOT NULL CHECK (service IN ('rpp', 'farma')),
    tracked_sheet_id INTEGER NOT NULL REFERENCES tracked_sheets (id) ON DELETE CASCADE,
    source_sheet_name VARCHAR(255) NOT NULL,
    source_row_num INTEGER NOT NULL,
    source_fingerprint VARCHAR(128) NOT NULL,
    platform_id BIGINT NULL,
    email VARCHAR(255) NULL,
    full_name VARCHAR(255) NULL,
    nickname VARCHAR(255) NULL,
    event_date TIMESTAMPTZ NULL,
    event_type VARCHAR(15) NOT NULL CHECK (event_type IN ('payment_click', 'payment_success')),
    amount NUMERIC(12, 2) NULL,
    raw_payment_value VARCHAR(255) NOT NULL,
    user_id INTEGER NULL REFERENCES users (id),
    farma_user_id INTEGER NULL REFERENCES farma_users (id),
    matched_user_tg_id BIGINT NULL,
    inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_payment_events_tracked_sheet_id_source_row_num
        UNIQUE (tracked_sheet_id, source_row_num),
    CONSTRAINT uq_payment_events_source_fingerprint
        UNIQUE (source_fingerprint)
);

CREATE INDEX IF NOT EXISTS ix_payment_events_service_event_date
    ON payment_events (service, event_date);

CREATE INDEX IF NOT EXISTS ix_payment_events_service_platform_id
    ON payment_events (service, platform_id);

CREATE INDEX IF NOT EXISTS ix_payment_events_user_id_event_date
    ON payment_events (user_id, event_date);

CREATE INDEX IF NOT EXISTS ix_payment_events_farma_user_id_event_date
    ON payment_events (farma_user_id, event_date);
