CREATE TABLE IF NOT EXISTS sfbt_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    join_date TIMESTAMPTZ NULL DEFAULT NOW(),
    utm_mark VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS sfbt_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES sfbt_users (id),
    event_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_sfbt_events_user_id_timestamp
    ON sfbt_events (user_id, timestamp);

ALTER TABLE tracked_sheets
    DROP CONSTRAINT IF EXISTS tracked_sheets_service_check;

ALTER TABLE tracked_sheets
    ADD CONSTRAINT tracked_sheets_service_check
    CHECK (service IN ('rpp', 'farma', 'sfbt'));

ALTER TABLE payment_events
    DROP CONSTRAINT IF EXISTS payment_events_service_check;

ALTER TABLE payment_events
    ADD CONSTRAINT payment_events_service_check
    CHECK (service IN ('rpp', 'farma', 'sfbt'));

ALTER TABLE payment_events
    ADD COLUMN IF NOT EXISTS sfbt_user_id INTEGER NULL REFERENCES sfbt_users (id);

CREATE INDEX IF NOT EXISTS ix_payment_events_sfbt_user_id_event_date
    ON payment_events (sfbt_user_id, event_date);


