CREATE TABLE IF NOT EXISTS telegram_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service VARCHAR(20) NULL CHECK (service IS NULL OR service IN ('rpp', 'farma', 'sfbt')),
    source_chat_id BIGINT NOT NULL,
    media_group_id VARCHAR(255) NULL,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('single', 'album')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('collecting', 'ready')),
    preview_text VARCHAR(200) NULL,
    items_count INTEGER NOT NULL DEFAULT 0,
    ready_after TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_telegram_templates_status_created_at
    ON telegram_templates (status, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_telegram_templates_collecting_media_group
    ON telegram_templates (source_chat_id, media_group_id, status);

CREATE INDEX IF NOT EXISTS ix_telegram_templates_status_ready_after
    ON telegram_templates (status, ready_after);

CREATE TABLE IF NOT EXISTS telegram_template_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id INTEGER NOT NULL REFERENCES telegram_templates (id) ON DELETE CASCADE,
    source_message_id BIGINT NOT NULL,
    content_type VARCHAR(30) NOT NULL,
    raw_message_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_template_items_template_message
        UNIQUE (template_id, source_message_id)
);

CREATE TABLE IF NOT EXISTS broadcasts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id INTEGER NOT NULL REFERENCES telegram_templates (id),
    service VARCHAR(20) NOT NULL CHECK (service IN ('rpp', 'farma', 'sfbt')),
    audience_type VARCHAR(50) NOT NULL,
    audience_filter JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('scheduled', 'sending', 'sent', 'cancelled', 'failed')
    ),
    scheduled_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ NULL,
    finished_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_broadcasts_status_scheduled_at
    ON broadcasts (status, scheduled_at);

CREATE INDEX IF NOT EXISTS ix_broadcasts_created_at
    ON broadcasts (created_at DESC);

CREATE TABLE IF NOT EXISTS broadcast_recipients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broadcast_id INTEGER NOT NULL REFERENCES broadcasts (id) ON DELETE CASCADE,
    tg_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('pending', 'processing', 'sent', 'failed', 'skipped')
    ),
    attempts INTEGER NOT NULL DEFAULT 0,
    locked_at TIMESTAMPTZ NULL,
    locked_by VARCHAR(100) NULL,
    next_attempt_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    sent_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_broadcast_recipients_broadcast_tg
        UNIQUE (broadcast_id, tg_id)
);

CREATE INDEX IF NOT EXISTS ix_broadcast_recipients_status_next_attempt_id
    ON broadcast_recipients (status, next_attempt_at, id);

CREATE INDEX IF NOT EXISTS ix_broadcast_recipients_broadcast_status
    ON broadcast_recipients (broadcast_id, status);