CREATE TABLE IF NOT EXISTS cbtbase_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    join_date TIMESTAMPTZ NULL DEFAULT NOW(),
    utm_mark VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS cbtbase_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES cbtbase_users (id),
    event_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_cbtbase_events_user_id_timestamp
    ON cbtbase_events (user_id, timestamp);

ALTER TABLE tracked_sheets
    ALTER COLUMN service TYPE VARCHAR(20);

ALTER TABLE tracked_sheets
    DROP CONSTRAINT IF EXISTS tracked_sheets_service_check;

ALTER TABLE tracked_sheets
    ADD CONSTRAINT tracked_sheets_service_check
    CHECK (service IN ('rpp', 'farma', 'sfbt', 'cbtbase'));

ALTER TABLE payment_events
    ALTER COLUMN service TYPE VARCHAR(20);

ALTER TABLE payment_events
    DROP CONSTRAINT IF EXISTS payment_events_service_check;

ALTER TABLE payment_events
    ADD CONSTRAINT payment_events_service_check
    CHECK (service IN ('rpp', 'farma', 'sfbt', 'cbtbase'));

ALTER TABLE payment_events
    ADD COLUMN IF NOT EXISTS cbtbase_user_id INTEGER NULL REFERENCES cbtbase_users (id);

CREATE INDEX IF NOT EXISTS ix_payment_events_cbtbase_user_id_event_date
    ON payment_events (cbtbase_user_id, event_date);

ALTER TABLE telegram_templates
    DROP CONSTRAINT IF EXISTS telegram_templates_service_check;

ALTER TABLE telegram_templates
    ADD CONSTRAINT telegram_templates_service_check
    CHECK (service IS NULL OR service IN ('rpp', 'farma', 'sfbt', 'cbtbase'));

ALTER TABLE broadcasts
    DROP CONSTRAINT IF EXISTS broadcasts_service_check;

ALTER TABLE broadcasts
    ADD CONSTRAINT broadcasts_service_check
    CHECK (service IN ('rpp', 'farma', 'sfbt', 'cbtbase'));
